version: "3.8"
services:
  # Nginx Service
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - database
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./backend/code:/usr/share/nginx/backend
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx-debug", "-g", "daemon off;"]

  # React Service
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/code/src:/app/src
      - ./frontend/code/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env

  # PHP Service
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/code:/usr/share/nginx/backend
      - ./backend/php.ini:/usr/local/etc/php/conf.d/local.ini
  
  # MySQL Service
  database:
    image: mysql:8.0.27
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doklimit
    volumes:
      - ./database/db:/var/lib/mysql
      - ./database/mysql.cnf:/etc/mysql/my.cnf

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   networks:
  #     - laravel